// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddRemote'](arg1, arg2, arg3, arg4);
}

export function AddTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddTunnel'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function DeleteRemote(arg1) {
  return window['go']['app']['App']['DeleteRemote'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function GetRemote(arg1) {
  return window['go']['app']['App']['GetRemote'](arg1);
}

export function GetRemotes() {
  return window['go']['app']['App']['GetRemotes']();
}

export function GetTunnels(arg1) {
  return window['go']['app']['App']['GetTunnels'](arg1);
}

export function RemoveTunnel(arg1, arg2) {
  return window['go']['app']['App']['RemoveTunnel'](arg1, arg2);
}

export function UpdateRemote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateRemote'](arg1, arg2, arg3, arg4, arg5);
}

export function WithEvents() {
  return window['go']['app']['App']['WithEvents']();
}
