// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRemote'](arg1, arg2, arg3, arg4, arg5);
}

export function AddTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTunnel'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetRemote(arg1) {
  return window['go']['main']['App']['GetRemote'](arg1);
}

export function GetRemotes() {
  return window['go']['main']['App']['GetRemotes']();
}

export function GetTunnels(arg1) {
  return window['go']['main']['App']['GetTunnels'](arg1);
}

export function RemoveRemote(arg1) {
  return window['go']['main']['App']['RemoveRemote'](arg1);
}

export function RemoveTunnel(arg1, arg2) {
  return window['go']['main']['App']['RemoveTunnel'](arg1, arg2);
}
