// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:number,arg2:string,arg3:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;
